### ISSUE TITLE
Unable to get ingredients in Spanish after .setLang("es")

### ISSUE THREAD

**Issue by realrodri** [openfoodfacts/openfoodfacts-java#14]
Hi!

I can't get the ingredients in Spanish of a product based on a barcode. I manually enter the barcode but the ingredients it returns are English only. I want to be able to get them on Spanish, if possible.

Code:

```
public static String getIngredients(String barCode){
    OpenFoodFactsWrapper wrapper = new OpenFoodFactsWrapperImpl();
    ProductResponse productResponse = wrapper.fetchProductByCode(barCode);
    productResponse.getProduct().setLang("es");
    
    return productResponse.getProduct().getIngredientsText();
}
```

After testing with the barcode: "5411188103387" (see the web: https://es.openfoodfacts.org/producto/5411188103387/alpro-vainilla), they appear in Spanish, but the returned string is not on Spanish.

Returned: soya  base (water, hulled  soya  beans 9,9%), sugar, stabiliser (pectins), calcium (tri-calcium phosphate), acidity regulators (citric acid, sodium citrates), carrot extract, sea salt, natural vanilla flavouring, flavourings, vanilla powder, antioxidants (tocopherol-rich extract, fatty acid esters of ascorbic acid), vitamins (b2, b12, d2), yogurt cultures (s, thermophilus, l, bulgaricus),

Thanks in advance!

**Comment by toudidel** [comment]
Request to API in your case is https://world.openfoodfacts.org/api/v0/product/5411188103387.json
Returned data underneath comes from response field _ingredients_text_, not from _ingredients_text_es_.

By the way your line `productResponse.getProduct().setLang("es")` does nothing, it's only a getter.

I'm agree it'd be nice to support all possible languages, but it may be a ittle silly to add all possible fields (with language suffixes) to model. For example: _ingredientsText, ingredientsTextEn, ingredientsTextEs, ingredientsTextFr, ingredientsTextNl_ and so on.
There is alternative way and have a generic map in model and get specific directly by key, but it's not elegant solution in my opinion.

**Comment by realrodri** [comment]
So how could I get only the Spanish ingredients? Meaning to make the API Request to: https://es.openfoodfacts.org/api/v0/product/5411188103387.json ?

Thanks!

**Comment by realrodri** [comment]
> I'll try to add support for generic fields which are unknown at compilation time.

But at this moment, does it mean it's unavailable to get Spanish ingredients with the API? If not, how could I make the API request to the es.openfoodfacts.org subdomain?

**Comment by realrodri** [comment]
> I'll try to add support for generic fields which are unknown at compilation time.

But at this moment, does it mean it's unavailable to get Spanish ingredients with the API? If not, how could I make the API request to the es.openfoodfacts.org subdomain?

**Comment by toudidel** [comment]
My wrapper always use main url (_https://world.openfoodfacts.org/api/v0_) but I can see no difference between request to url _https://world.openfoodfacts.org/api/v0_ and for example _https://es.openfoodfacts.org/api/v0_.

The only small difference is in image urls. For example `https://images.openfoodfacts.org/images/products/541/118/810/3387/front_es.187.200.jpg` instead of `https://images.openfoodfacts.org/images/products/541/118/810/3387/front_en.177.200.jpg`

**Comment by realrodri** [comment]
> My wrapper always use main url (_https://world.openfoodfacts.org/api/v0_) but I can see no difference between request to url _https://world.openfoodfacts.org/api/v0_ and for example _https://es.openfoodfacts.org/api/v0_.
> 
> The only small difference is in image urls. For example `https://images.openfoodfacts.org/images/products/541/118/810/3387/front_es.187.200.jpg` instead of `https://images.openfoodfacts.org/images/products/541/118/810/3387/front_en.177.200.jpg`

I know, it's only for the ingredients thing. How can I change the URL of the API request?

**Comment by realrodri** [comment]
> My wrapper always use main url (_https://world.openfoodfacts.org/api/v0_) but I can see no difference between request to url _https://world.openfoodfacts.org/api/v0_ and for example _https://es.openfoodfacts.org/api/v0_.
> 
> The only small difference is in image urls. For example `https://images.openfoodfacts.org/images/products/541/118/810/3387/front_es.187.200.jpg` instead of `https://images.openfoodfacts.org/images/products/541/118/810/3387/front_en.177.200.jpg`

But how can I get the ingredients in other languages? Would that be possible with the current Java API?

**Comment by realrodri** [comment]
> openfoodfacts-java is only a wrapper for API and in current version it does not support fields are absent in current model (in class [Product](https://github.com/openfoodfacts/openfoodfacts-java/blob/main/src/main/java/pl/coderion/model/Product.java))

I see... I wish there was a method to obtain the Spanish ingredients as you suggested before :(

**Comment by realrodri** [comment]
Update: Git Cloned' and changed the "ingredients_text" variable on the @JsonProperty and compiling it myself, I managed to get the Spanish ingredients. However, it would be great if the API natively offers all languages ingredients. But by this time, this is the only workaround I found.

I only need to convert this dependency to Gradle and implement it on my project. If somebody in the future encounters this comment, here is the .jar compiled, but be careful, it's only meant for Spanish products. It won't return you on any other language, only in Spanish.

If you want to use it, get it [here](https://anonymfile.com/9bjb/openfoodfacts-java-wrapper-094-snapshot.jar).

I'd recommend to not close this GitHub issue as a recommendation for a TODO to personalize the experience of the API.

Thanks again! :)

**Comment by void0x23** [comment]
Hello, i'll try to add a generic way to get specific language code from the general product result in the new version i'm developing, unfortunately the openapi definition is not fully usable and this makes the work defenitely more verbose cause i have to write manually all the models.
