### ISSUE TITLE
Should I be getting this response???

### ISSUE THREAD

**Issue by muhammadmkhan** [openfoodfacts/openfoodfacts-java#2]
Shoud I be getting this response??

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/ymnek/.m2/repository/pl/coderion/openfoodfacts-java-wrapper/0.9.3/openfoodfacts-java-wrapper-0.9.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/ymnek/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
ProductResponse(product=Product(images=Images(other={1={sizes={100={h=71, w=100}, 400={h=284, w=400}, full={h=1089, w=1536}}, uploaded_t=1345799270, uploader=openfoodfacts-contributors}, 2={sizes={100={h=100, w=72}, 400={h=400, w=289}, full={h=1812, w=1311}}, uploaded_t=1345799309, uploader=andre}, 3={sizes={100={h=72, w=100}, 400={h=289, w=400}, full={h=927, w=1281}}, uploaded_t=1345799558, uploader=andre}, 4={sizes={100={h=72, w=100}, 400={h=289, w=400}, full={h=927, w=1281}}, uploaded_t=1345799666, uploader=andre}, 5={sizes={100={h=100, w=54}, 400={h=400, w=216}, full={h=1611, w=870}}, uploaded_t=1345799925, uploader=andre}, front={geometry=0x0--4--4, imgid=2, normalize=null, rev=6, sizes={100={h=100, w=72}, 200={h=200, w=145}, 400={h=400, w=289}, full={h=1812, w=1311}}, white_magic=null}, front_en={geometry=0x0--4--4, imgid=2, normalize=null, rev=6, sizes={100={h=100, w=72}, 200={h=200, w=145}, 400={h=400, w=289}, full={h=1812, w=1311}}, white_magic=null}, ingredients={geometry=0x0--3--3, imgid=4, normalize=checked, rev=10, sizes={100={h=72, w=100}, 200={h=145, w=200}, 400={h=289, w=400}, full={h=927, w=1281}}, white_magic=null}, ingredients_en={geometry=0x0--3--3, imgid=4, normalize=checked, rev=10, sizes={100={h=72, w=100}, 200={h=145, w=200}, 400={h=289, w=400}, full={h=927, w=1281}}, white_magic=null}, nutrition={geometry=0x0--4--4, imgid=5, normalize=checked, rev=12, sizes={100={h=100, w=54}, 200={h=200, w=108}, 400={h=400, w=216}, full={h=1611, w=870}}, white_magic=null}, nutrition_en={geometry=0x0--4--4, imgid=5, normalize=checked, rev=12, sizes={100={h=100, w=54}, 200={h=200, w=108}, 400={h=400, w=216}, full={h=1611, w=870}}, white_magic=null}}), ingredients=[Ingredient(fromPalmOil=null, id=en:noodle, origin=null, percent=null, rank=1, text=Noodle, vegan=null, vegetarian=null), Ingredient(fromPalmOil=null, id=en:water, origin=null, percent=null, rank=2, text=water, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:seasoning packet, origin=null, percent=null, rank=3, text=seasoning packet, vegan=null, vegetarian=null), Ingredient(fromPalmOil=null, id=en:sugar, origin=null, percent=null, rank=4, text=sugar, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:hydrolysed-soy-protein, origin=null, percent=null, rank=5, text=hydrolyzed soy protein, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:green-onion, origin=null, percent=null, rank=6, text=green onion, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:corn-maltodextrin, origin=null, percent=null, rank=7, text=corn maltodextrin, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:spice, origin=null, percent=null, rank=8, text=spice, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:e330, origin=null, percent=null, rank=9, text=citric acid, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:sea-salt, origin=null, percent=null, rank=10, text=sea salt, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:paprika, origin=null, percent=null, rank=11, text=paprika, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:e551, origin=null, percent=null, rank=12, text=silicon dioxide, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:yeast-extract, origin=null, percent=null, rank=13, text=yeast extract, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:rice, origin=null, percent=null, rank=0, text=rice, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:peanut, origin=null, percent=null, rank=0, text=peanut, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:paprika, origin=null, percent=null, rank=0, text=including paprika, vegan=yes, vegetarian=yes), Ingredient(fromPalmOil=null, id=en:colour, origin=null, percent=null, rank=0, text=color, vegan=null, vegetarian=null), Ingredient(fromPalmOil=null, id=en:added to make free flowing, origin=null, percent=null, rank=0, text=added to make free flowing, vegan=null, vegetarian=null)], languagesCodes=LanguagesCodes(en=6, fr=null, pl=null), nutrientLevels=NutrientLevels(fat=moderate, salt=moderate, saturatedFat=moderate, sugars=high), nutriments=Nutriments(calcium=0.038, calciumValue=38.0, calcium100G=0.038, calciumServing=0.0198, calciumUnit=mg, carbohydrates=71.15, carbohydratesValue=71.15, carbohydrates100G=71.15, carbohydratesServing=37.0, carbohydratesUnit=g, carbonFootprintFromKnownIngredientsProduct=0.0, carbonFootprintFromKnownIngredients100G=0.0, carbonFootprintFromKnownIngredientsServing=0.0, cholesterol=0.0, cholesterolValue=0.0, cholesterol100G=0.0, cholesterolServing=0.0, cholesterolUnit=mg, energy=1611, energyKcal=385, energyKj=0, energyValue=385, energyKcalValue=385, energyKjValue=0, energy100G=1611, energyKcal100G=385, energyKj100G=0, energyServing=838, energyKcalServing=200, energyKjServing=0, energyUnit=kcal, energyKcalUnit=kcal, energyKjUnit=null, fat=7.69, fatValue=7.69, fat100G=7.69, fatServing=4.0, fatUnit=g, fiber=1.9, fiberValue=1.9, fiber100G=1.9, fiberServing=0.988, fiberUnit=g, fruitsVegetablesNutsEstimateFromIngredients100G=0.0, iron=6.9E-4, ironValue=0.69, iron100G=6.9E-4, ironServing=3.59E-4, ironUnit=mg, novaGroup=4.0, novaGroup100G=4.0, novaGroupServing=4.0, proteins=9.62, proteinsValue=9.62, proteins100G=9.62, proteinsServing=5.0, proteinsUnit=g, salt=0.72, saltValue=720.0, salt100G=0.72, saltServing=0.374, saltUnit=mg, saturatedFat=1.92, saturatedFatValue=1.92, saturatedFat100G=1.92, saturatedFatServing=0.998, saturatedFatUnit=g, sodium=0.288, sodiumValue=288.0, sodium100G=0.288, sodiumServing=0.15, sodiumUnit=mg, sugars=13.46, sugarsValue=13.46, sugars100G=13.46, sugarsServing=7.0, sugarsUnit=g, transFat=0.0, transFatValue=0.0, transFat100G=0.0, transFatServing=0.0, transFatUnit=g, vitaminA=1.155E-4, vitaminAValue=385.0, vitaminA100G=1.155E-4, vitaminAServing=6.01E-5, vitaminAUnit=IU, vitaminC=0.0, vitaminCValue=0.0, vitaminC100G=0.0, vitaminCServing=0.0, vitaminCUnit=mg, vitaminD=0.0, vitaminDValue=0.0, vitaminD100G=0.0, vitaminDServing=0.0, vitaminDUnit=null, other={nutrition-score-fr=4, nutrition-score-fr_100g=4}), selectedImages=SelectedImages(front=SelectedImage(display=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.400.jpg, fr=null, pl=null), small=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.200.jpg, fr=null, pl=null), thumb=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.100.jpg, fr=null, pl=null)), ingredients=SelectedImage(display=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.400.jpg, fr=null, pl=null), small=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.200.jpg, fr=null, pl=null), thumb=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.100.jpg, fr=null, pl=null)), nutrition=SelectedImage(display=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.400.jpg, fr=null, pl=null), small=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.200.jpg, fr=null, pl=null), thumb=SelectedImageItem(en=https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.100.jpg, fr=null, pl=null))), sources=[Source(fields=[brands, countries], id=usda-ndb, images=[], importT=1489067409, manufacturer=null, name=null, url=https://api.nal.usda.gov/ndb/reports/?ndbno=45108002&type=f&format=json&api_key=DEMO_KEY), Source(fields=[product_name_en, categories, brand_owner, data_sources, nutrition_data_per, serving_size, ingredients_text_en, nutrients.calcium_unit, nutrients.calcium_value, nutrients.carbohydrates_value, nutrients.cholesterol_unit, nutrients.cholesterol_value, nutrients.energy_value, nutrients.energy-kcal_value, nutrients.fat_value, nutrients.fiber_value, nutrients.iron_unit, nutrients.iron_value, nutrients.proteins_value, nutrients.salt_unit, nutrients.salt_value, nutrients.saturated-fat_value, nutrients.sugars_value, nutrients.trans-fat_unit, nutrients.trans-fat_value, nutrients.vitamin-a_unit, nutrients.vitamin-a_value, nutrients.vitamin-c_unit, nutrients.vitamin-c_value], id=database-usda, images=[], importT=1587581231, manufacturer=null, name=database-usda, url=null)], additivesN=1, additivesOldN=2, additivesOriginalTags=[en:e330], additivesOldTags=[en:e330, en:e551], additivesPrevOriginalTags=[en:e330], additivesDebugTags=[], additivesTags=[en:e330], allergens=, allergensFromIngredients=, allergensFromUser=(en) , allergensHierarchy=[], allergensLc=null, allergensTags=[], aminoAcidsPrevTags=[], aminoAcidsTags=[], brands=Thai Kitchen,Simply Asia, brandsDebugTags=[], brandsTags=[thai-kitchen, simply-asia], carbonFootprintPercentOfKnownIngredients=null, carbonFootprintFromKnownIngredientsDebug=null, categories=Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Cereals and their products, Noodles, Rice Noodles, categoriesHierarchy=[en:plant-based-foods-and-beverages, en:plant-based-foods, en:cereals-and-potatoes, en:cereals-and-their-products, en:noodles, en:Rice Noodles], categoriesLc=en, categoriesPropertiesTags=[all-products, categories-known, agribalyse-food-code-unknown, agribalyse-proxy-food-code-unknown, ciqual-food-code-unknown, agribalyse-unknown], categoriesTags=[en:plant-based-foods-and-beverages, en:plant-based-foods, en:cereals-and-potatoes, en:cereals-and-their-products, en:noodles, en:rice-noodles], checkersTags=[], citiesTags=[], code=0737628064502, codesTags=[code-13, 0737628064xxx, 073762806xxxx, 07376280xxxxx, 0737628xxxxxx, 073762xxxxxxx, 07376xxxxxxxx, 0737xxxxxxxxx, 073xxxxxxxxxx, 07xxxxxxxxxxx, 0xxxxxxxxxxxx], comparedToCategory=en:noodles, complete=1, completedT=1355184837, completeness=0.8, conservationConditions=null, countries=France, United States, countriesHierarchy=[en:france, en:united-states], countriesLc=en, countriesDebugTags=[], countriesTags=[en:france, en:united-states], correctorsTags=[andre, thierrym, usda-ndb-import, smartchef, org-database-usda], createdT=1345799269, creator=openfoodfacts-contributors, dataQualityBugsTags=[], dataQualityErrorsTags=[], dataQualityInfoTags=[en:ingredients-percent-analysis-ok], dataQualityTags=[en:ingredients-percent-analysis-ok, en:nutrition-value-very-high-for-category-sugars], dataQualityWarningsTags=[en:nutrition-value-very-high-for-category-sugars], dataSources=Databases, database-usda, dataSourcesTags=[databases, database-usda], debugParamSortedLangs=[en], editorsTags=[manu1400, upcbot, smartchef, openfoodfacts-contributors, usda-ndb-import, org-database-usda, andre, thierrym], embCodes=, embCodesDebugTags=[], embCodesOrig=, embCodesTags=[], entryDatesTags=[2012-08-24, 2012-08, 2012], expirationDate=, expirationDateDebugTags=[], fruitsVegetablesNuts100GEstimate=0, genericName=Rice Noodles, id=737628064502, _id=0737628064502, imageFrontSmallUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.200.jpg, imageFrontThumbUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.100.jpg, imageFrontUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.400.jpg, imageIngredientsUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.400.jpg, imageIngredientsSmallUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.200.jpg, imageIngredientsThumbUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/ingredients_en.10.100.jpg, imageNutritionSmallUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.200.jpg, imageNutritionThumbUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.100.jpg, imageNutritionUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/nutrition_en.12.400.jpg, imageSmallUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.200.jpg, imageThumbUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.100.jpg, imageUrl=https://static.openfoodfacts.org/images/products/073/762/806/4502/front_en.6.400.jpg, informersTags=[andre, manu1400, thierrym, upcbot, smartchef, org-database-usda], ingredientsAnalysisTags=[en:palm-oil-content-unknown, en:vegan-status-unknown, en:vegetarian-status-unknown], ingredientsDebug=[RICE NOODLES , (, (, null, null, RICE, ,, null, null, null,  WATER), ,, null, null, null,  SEASONING PACKET , (, (, null, null, PEANUT, ,, null, null, null,  SUGAR, ,, null, null, null,  SALT, ,, null, null, null,  CORN STARCH, ,, null, null, null,  SPICES , [, [, null, null, CHILI, ,, null, null, null,  CINNAMON, ,, null, null, null,  PEPPER, ,, null, null, null,  CUMIN, ,, null, null, null,  CLOVE], ,, null, null, null,  HYDRDLYZED SOY PROTEIN, ,, null, null, null,  GREEN ONIONS, ,, null, null, null,  CITRIC ACID, ,, null, null, null,  PEANUT OIL, ,, null, null, null,  SESAME OIL, ,, null, null, null,  , :, :, null, null,  NATURAL FLAVOR , :, :, null, null,  ).], ingredientsFromOrThatMayBeFromPalmOilN=0, ingredientsFromPalmOilTags=[], ingredientsFromPalmOilN=0, ingredientsHierarchy=[en:noodle, en:dough, en:water, en:seasoning packet, en:sugar, en:hydrolysed-soy-protein, en:protein, en:vegetable-protein, en:hydrolysed-vegetable-protein, en:soy-protein, en:green-onion, en:vegetable, en:root-vegetable, en:onion, en:corn-maltodextrin, en:maltodextrins, en:spice, en:e330, en:sea-salt, en:salt, en:paprika, en:seed, en:pepper, en:e551, en:yeast-extract, en:yeast, en:rice, en:peanut, en:nut, en:colour, en:added to make free flowing], ingredientsIdsDebug=[rice-noodles, rice, water, seasoning-packet, peanut, sugar, salt, corn-starch, spices, chili, cinnamon, pepper, cumin, clove, hydrdlyzed-soy-protein, green-onions, citric-acid, peanut-oil, sesame-oil, natural-flavor], ingredientsN=18, ingredientsNTags=[18, 11-20], ingredientsOriginalTags=[en:noodle, en:water, en:seasoning packet, en:sugar, en:hydrolysed-soy-protein, en:green-onion, en:corn-maltodextrin, en:spice, en:e330, en:sea-salt, en:paprika, en:e551, en:yeast-extract, en:rice, en:peanut, en:paprika, en:colour, en:added to make free flowing], ingredientsTags=[en:noodle, en:dough, en:water, en:seasoning-packet, en:sugar, en:hydrolysed-soy-protein, en:protein, en:vegetable-protein, en:hydrolysed-vegetable-protein, en:soy-protein, en:green-onion, en:vegetable, en:root-vegetable, en:onion, en:corn-maltodextrin, en:maltodextrins, en:spice, en:e330, en:sea-salt, en:salt, en:paprika, en:seed, en:pepper, en:e551, en:yeast-extract, en:yeast, en:rice, en:peanut, en:nut, en:colour, en:added-to-make-free-flowing], ingredientsText=Noodle: rice, water. seasoning packet: peanut, sugar, hydrolyzed soy protein, green onion, corn maltodextrin, spice (including paprika), citric acid, sea salt, extractives of paprika (color), silicon dioxide (added to make free flowing), yeast extract., ingredientsTextDebug=RICE NOODLES (RICE, WATER), SEASONING PACKET (PEANUT, SUGAR, SALT, CORN STARCH, SPICES [CHILI, CINNAMON, PEPPER, CUMIN, CLOVE], HYDRDLYZED SOY PROTEIN, GREEN ONIONS, CITRIC ACID, PEANUT OIL, SESAME OIL, : NATURAL FLAVOR : )., ingredientsTextWithAllergens=Noodle: rice, water. seasoning packet: peanut, sugar, hydrolyzed soy protein, green onion, corn maltodextrin, spice (including paprika), citric acid, sea salt, extractives of paprika (color), silicon dioxide (added to make free flowing), yeast extract., ingredientsThatMayBeFromPalmOilN=0, ingredientsThatMayBeFromPalmOilTags=[], interfaceVersionCreated=20120622, interfaceVersionModified=20120622, keywords=[kit, plant-based, thai, food, and, simply, gluten-free, beverage, noodle, cereal, peanut, thailand, their, stir-fry, rice, potatoe, include, asia, seasoning, kitchen, product], knownIngredientsN=29, labels=Gluten-free, labelsHierarchy=[en:gluten-free], labelsLc=en, labelsPrevHierarchy=[en:gluten-free], labelsPrevTags=[en:gluten-free], labelsTags=[en:gluten-free], labelsDebugTags=null, lang=en, langDebugTags=[], languagesHierarchy=[en:english], languagesTags=[en:english, en:1], lastEditDatesTags=[2020-04-22, 2020-04, 2020], lastEditor=org-database-usda, lastImageDatesTags=[2012-08-24, 2012-08, 2012], lastImageT=1345799925, lastModifiedBy=org-database-usda, lastModifiedT=1587581231, lc=en, link=, linkDebugTags=[], manufacturingPlaces=, manufacturingPlacesDebugTags=[], manufacturingPlacesTags=[], maxImgid=5, mineralsPrevTags=[], mineralsTags=[], miscTags=[en:nutrition-fruits-vegetables-nuts-estimate-from-ingredients, en:nutrition-all-nutriscore-values-known, en:nutriscore-computed, en:ecoscore-not-computed, en:main-countries-fr-product-name-not-in-country-language, en:main-countries-fr-ingredients-not-in-country-language, en:main-countries-fr-no-data-in-country-language], netWeightUnit=null, netWeightValue=null, nutritionDataPer=100g, nutritionScoreWarningNoFruitsVegetablesNuts=0, noNutritionData=, novaGroup=4, novaGroups=4, novaGroupDebug= -- ingredients/en:sugar : 3 -- ingredients/en:colour : 4, novaGroupTags=null, novaGroupsTags=[en:4-ultra-processed-food-and-drink-products], nucleotidesPrevTags=[], nucleotidesTags=[], nutrientLevelsTags=[en:fat-in-moderate-quantity, en:saturated-fat-in-moderate-quantity, en:sugars-in-high-quantity, en:salt-in-moderate-quantity], nutritionData=on, nutritionDataPerDebugTags=[], nutritionDataPrepared=, nutritionDataPreparedPer=100g, nutritionGrades=c, nutritionScoreBeverage=0, nutritionScoreDebug=null, nutritionScoreWarningNoFiber=0, nutritionGradesTags=[c], origins=Thailand, originsDebugTags=null, originsTags=[en:thailand], otherInformation=null, otherNutritionalSubstancesTags=[], packaging=Cellophane,Carton, packagingDebugTags=[], packagingTags=[cellophane, carton], photographersTags=[openfoodfacts-contributors, andre], pnnsGroups1=Cereals and potatoes, pnnsGroups2=Cereals, pnnsGroups1Tags=[cereals-and-potatoes, known], pnnsGroups2Tags=[cereals, known], popularityKey=19900000005, producerVersionId=null, productName=Thai peanut noodle kit includes stir-fry rice noodles & thai peanut seasoning, productQuantity=155, purchasePlaces=, purchasePlacesDebugTags=[], purchasePlacesTags=[], qualityTags=null, quantity=155 g, quantityDebugTags=[], recyclingInstructionsToDiscard=null, rev=19, servingQuantity=52, servingSize=0.333 PACKAGE (52 g), servingSizeDebugTags=[], sortkey=1587581231, states=en:to-be-checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded, statesHierarchy=[en:to-be-checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded], statesTags=[en:to-be-checked, en:complete, en:nutrition-facts-completed, en:ingredients-completed, en:expiration-date-to-be-completed, en:packaging-code-to-be-completed, en:characteristics-completed, en:categories-completed, en:brands-completed, en:packaging-completed, en:quantity-completed, en:product-name-completed, en:photos-validated, en:photos-uploaded], stores=, storesDebugTags=[], storesTags=[], traces=en:peanuts, tracesFromIngredients=, tracesHierarchy=[en:peanuts], tracesDebugTags=[], tracesFromUser=(en) en:peanuts, tracesLc=null, tracesTags=[en:peanuts], unknownIngredientsN=2, unknownNutrientsTags=[], updateKey=main-countries, vitaminsPrevTags=[], vitaminsTags=[], other={added_countries_tags=[], additives_tags_n=null, brand_owner=Simply Asia Foods, Inc., brand_owner_imported=Simply Asia Foods, Inc., categories_imported=Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Cereals and their products, Noodles, categories_old=Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Cereals and their products, Noodles, Rice Noodles, categories_properties={}, category_properties={}, checkers=[], ciqual_food_name_tags=[unknown], correctors=[andre, thierrym], countries_imported=United States, data_sources_imported=Databases, database-usda, ecoscore_data={adjustments={origins_of_ingredients={aggregated_origins=[{origin=en:thailand, percent=100}], epi_score=0, epi_value=-5, origins_from_origins_field=[en:thailand], transportation_score_be=12, transportation_score_ch=9, transportation_score_de=12, transportation_score_es=25, transportation_score_fr=0, transportation_score_ie=0, transportation_score_it=16, transportation_score_lu=3, transportation_score_nl=12, transportation_value_be=2, transportation_value_ch=1, transportation_value_de=2, transportation_value_es=4, transportation_value_fr=0, transportation_value_ie=0, transportation_value_it=2, transportation_value_lu=0, transportation_value_nl=2, value_be=-3, value_ch=-4, value_de=-3, value_es=-1, value_fr=-5, value_ie=-5, value_it=-3, value_lu=-5, value_nl=-3}, packaging={non_recyclable_and_non_biodegradable_materials=1, packagings=[{ecoscore_material_score=0, ecoscore_shape_ratio=1, material=en:unknown, non_recyclable_and_non_biodegradable=maybe, shape=en:unknown}], score=0, value=-10, warning=unscored_shape}, production_system={warning=no_label}, threatened_species={}}, agribalyse={warning=missing_agribalyse_match}, missing={agb_category=1, labels=1, packagings=1}, missing_agribalyse_match_warning=1, status=unknown}, ecoscore_grade=unknown, ecoscore_tags=[unknown], editors=[, thierrym, manu1400, andre, upcbot], emb_codes_20141016=, generic_name_en=Rice Noodles, generic_name_en_debug_tags=[], informers=[andre, manu1400, thierrym], ingredients_percent_analysis=1, ingredients_text_en=Noodle: rice, water. seasoning packet: peanut, sugar, hydrolyzed soy protein, green onion, corn maltodextrin, spice (including paprika), citric acid, sea salt, extractives of paprika (color), silicon dioxide (added to make free flowing), yeast extract., ingredients_text_en_debug_tags=[], ingredients_text_en_imported=Noodle: rice, water. seasoning packet: peanut, sugar, hydrolyzed soy protein, green onion, corn maltodextrin, spice (including paprika), citric acid, sea salt, extractives of paprika (color), silicon dioxide (added to make free flowing), yeast extract., ingredients_text_with_allergens_en=Noodle: rice, water. seasoning packet: peanut, sugar, hydrolyzed soy protein, green onion, corn maltodextrin, spice (including paprika), citric acid, sea salt, extractives of paprika (color), silicon dioxide (added to make free flowing), yeast extract., languages={en:english=6}, lc_imported=en, main_countries_tags=[], new_additives_n=1, nutriscore_data={energy=1611, energy_points=4, energy_value=1611, fiber=1.9, fiber_points=1, fiber_value=1.9, fruits_vegetables_nuts_colza_walnut_olive_oils=0, fruits_vegetables_nuts_colza_walnut_olive_oils_points=0, fruits_vegetables_nuts_colza_walnut_olive_oils_value=0, grade=c, is_beverage=0, is_cheese=0, is_fat=0, is_water=0, negative_points=10, positive_points=6, proteins=9.62, proteins_points=5, proteins_value=9.62, saturated_fat=1.92, saturated_fat_points=1, saturated_fat_ratio=24.9674902470741, saturated_fat_ratio_points=3, saturated_fat_ratio_value=25, saturated_fat_value=1.9, score=4, sodium=288, sodium_points=3, sodium_value=288, sugars=13.46, sugars_points=2, sugars_value=13.46}, nutriscore_grade=c, nutriscore_score=4, nutriscore_score_opposite=-4, nutrition_data_per_imported=100g, nutrition_data_prepared_per_debug_tags=[], nutrition_data_prepared_per_imported=100g, nutrition_grade_fr=c, nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients=1, nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value=0, origins_hierarchy=[en:thailand], origins_lc=en, origins_old=Thailand, packagings=[{material=en:unknown, shape=en:unknown}], photographers=[andre], popularity_tags=[bottom-25-percent-scans-2019, bottom-20-percent-scans-2019, top-85-percent-scans-2019, top-90-percent-scans-2019, top-50000-it-scans-2019, top-100000-it-scans-2019, top-country-it-scans-2019, top-100000-scans-2020, at-least-5-scans-2020, top-75-percent-scans-2020, top-80-percent-scans-2020, top-85-percent-scans-2020, top-90-percent-scans-2020, top-10-by-scans-2020, top-50-by-scans-2020, top-100-by-scans-2020, top-500-by-scans-2020, top-1000-by-scans-2020, top-5000-by-scans-2020, top-10000-by-scans-2020, top-50000-by-scans-2020, top-100000-by-scans-2020, top-country-by-scans-2020, top-5000-ca-scans-2020, top-10000-ca-scans-2020, top-50000-ca-scans-2020, top-100000-ca-scans-2020, top-50000-be-scans-2020, top-100000-be-scans-2020], product_name_en=Thai peanut noodle kit includes stir-fry rice noodles & thai peanut seasoning, product_name_en_debug_tags=[], product_name_en_imported=Thai peanut noodle kit includes stir-fry rice noodles & thai peanut seasoning, removed_countries_tags=[], scans_n=10, serving_size_imported=0.333 PACKAGE (52 g), sources_fields={org-database-usda={available_date=2019-09-25T00:00:00Z, fdc_category=All Noodles, fdc_data_source=LI, fdc_id=628190, modified_date=2019-09-25T00:00:00Z, publication_date=2019-12-06T00:00:00Z}}, unique_scans_n=5}), code=0737628064502, status=true, statusVerbose=product found)

**Comment by toudidel** [comment]
You asked for product with code 0737628064502 and it's the whole response (object with filled fields) for that.
Is there any problem?

**Comment by muhammadmkhan** [comment]
I don't know if this is the response I should be getting. Actually I am new at this. I wanted to be ssure that this is the response.

**Comment by toudidel** [comment]
This is OK. This is a text representation of your object with product data.

**Comment by muhammadmkhan** [comment]
shouldn't I be getting specific values in return for this related to product

**Comment by muhammadmkhan** [comment]
So now I have to parse this am I right??

**Comment by muhammadmkhan** [comment]
And if so can you share some content for it. If you know some good resources.

**Comment by toudidel** [comment]
_shouldn't I be getting specific values in return for this related to product_
There are some specific values, for example amount of calcium in field product.nutriments.calciumValue

_So now I have to parse this am I right??_
You don't have to parse anything. It's just simple POJO and contains all the data.
