### ISSUE TITLE
NoSuchMethodError - when trying to test the java wrapper

### ISSUE THREAD

**Issue by Ben-21** [openfoodfacts/openfoodfacts-java#22]
### What
I am getting the following:
java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.LoggerContext.setMDCAdapter(org.slf4j.spi.MDCAdapter)'
when trying to run a test of the wrapper.
I am running a spring boot app, which you can find here: [my-app](https://github.com/Ben-21/fridge-manager)

I am new to this stuff, so maybe I am completely missing something here...
Are you still developing the wrapper (because the last commits to source code files is quite a time ago)?

### Steps to reproduce the behavior:
1. checkout branch "try_api_access"
2. Go to 'GetAllImageInfosTest'
3. Click on run the test
4. See error: java.lang.NoSuchMethodError: 'void ch.qos.logback.classic.LoggerContext.setMDCAdapter(org.slf4j.spi.MDCAdapter)'

### Screenshots
![image](https://github.com/openfoodfacts/openfoodfacts-java/assets/118177877/1ffe9ab6-cfd0-4b56-9f55-7e277bb83c5d)

**Comment by teolemon** [comment]
We would need help maintening the Wrapper, indeed @Ben-21 :-)

**Comment by Ben-21** [comment]
> We would need help maintening the Wrapper, indeed @Ben-21 :-)

Ah, ok I see 🙂
When I am more experienced, I will come back to you 😉. For the moment I will switch to using webclient instead.

**Comment by sriganth3** [comment]
@teolemon, I would like to contribute.
@Ben-21, branch you mentioned is not present in repo link shared.
