### ISSUE TITLE
Not able to use it with Gradle

### ISSUE THREAD

**Issue by shervinkoushan** [openfoodfacts/openfoodfacts-java#9]
I am trying to use this in an Android app, but the following exception occurs: 

`Caused by: java.lang.RuntimeException: Duplicate class ch.qos.logback.classic.AsyncAppender found in modules jetified-logback-classic-1.2.3 (ch.qos.logback:logback-classic:1.2.3) and jetified-openfoodfacts-java-wrapper-0.9.3 (pl.coderion:openfoodfacts-java-wrapper:0.9.3)
`

I used `    implementation("pl.coderion:openfoodfacts-java-wrapper:0.9.3")
` in Gradle

**Comment by toudidel** [comment]
Have you your project somewhere on Github ready to build?

**Comment by shervinkoushan** [comment]
It happens even with an "empty" project. Here is a sample: https://github.com/shervinkoushan/sample

Please open the project in Android Studio and run the app. Observe the output in the Build terminal

**Comment by toudidel** [comment]
I'm afraid I don't know what can be a problem with your project. But I don't think it's simply some problem of Gradle.

I created simple Boot Spring [project](https://github.com/toudidel/openfoodfacts-gradle-sample) using Gradle with one simple endpoint to check how the dependency work in gradle project.
When you run and go to http://localhost:8080/ it works good and product data is properly fetched from OpenFoodFacts API.
